export const projects = [
  {
    id: 108,
    title: "Reddit (Clone)",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/reddit-clone/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/reddit-clone/2.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/reddit-clone/3.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/reddit-clone/4.png",
    ],
    link: "https://reddit-clone-ib.vercel.app",
    source: "https://github.com/israel-bonilla/reddit-clone",
    description: "A full-stack clone of Reddit with post/comment/vote functionality and Reddit sign-in.",
    techsUsed: ["Next.js/React", "PostgreSQL/SQL", "GraphQL/Apollo", "Supabase", "StepZen", "TypeScript", "Tailwind CSS"],
    features: ["Dynamic routing for subreddits, posts, and users", "Fetches posts based on GraphQL queries made to the PostgreSQL back-end", "Responsive design with Tailwind CSS", "Reddit Authentication/Sign-in", "SQL mutations to add posts, comments, and votes managed by Supabase database"],
  },
  {
    id: 101,
    title: "Louphira",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/2.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/3.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/4.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/5.png",
    ],
    link: "https://louphira.vercel.app/",
    source: "https://github.com/israel-bonilla/Louphira-Shop-Demo",
    description: "Home decoration and design ecommerce store front-end, with Stripe checkout.",
    techsUsed: ["Next.js", "React", "Recoil", "Sass Modules", "Stripe API", "next/router"],
    features: ["Server Side Rendering", "Stripe Checkout", "Shopping cart functionality"],
  },
  {
    id: 102,
    title: "Kajebu",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/2.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/3.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/4.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/5.png",
    ],
    link: "https://kajebu.vercel.app/",
    source: "https://github.com/israel-bonilla/kajebu",
    description: "Front-end clone of Kajabi dashboard, an online knowledge business platform.",
    techsUsed: ["Next.js", "React", "Recoil", "Sass Modules", "next/router"],
    features: ["User friendly UI/UX", "Modularized business tools and resources", "Products, pipelines, landing pages, marketing, CRM, and more all-in-one platform."],
  },
  {
    id: 103,
    title: "Weather App",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/weather-app/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/weather-app/2.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/weather-app/3.png",
    ],
    link: "https://weather-app-ib.vercel.app",
    source: "https://github.com/israel-bonilla/Weather-App",
    description: "A simple weather app that uses a custom React hook with the Geolocation API to broadcast the weather in your location.",
    techsUsed: ["React.js", "Redux", "Tailwind CSS", "Javascript", "Geolocation API", "OpenWeatherMap API", "Fetch API"],
    features: ["Temperature, precipitation, and wind (speed & direction) 24 hour broadcast", "7 day forecast", "Based on user's geolocation", "In Fahrenheit and Celsius", "Humidity indicator"],
  },
  {
    id: 104,
    title: "Hulu (Clone)",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/hulu-clone/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/hulu-clone/2.png",
    ],
    link: "https://hulu-clone-ib.vercel.app",
    source: "https://github.com/israel-bonilla/hulu-clone",
    description: "A front-end clone of Hulu, a movie streaming service.",
    techsUsed: ["Next.js", "React", "Tailwind CSS", "Server Side Rendering", "TMDB API", "Fetch API", "next/router"],
    features: ["Uses movie data from The Movie Database (TMDB)", "Fetches current movies from genres: trending, top rated, action, comedy, horror, and 6 more", "Responsive UI on all screens"],
  },
  {
    id: 105,
    title: "Instagram (Clone)",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/ig-clone/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/ig-clone/2.png",
    ],
    link: "https://ig-clone-ib.vercel.app",
    source: "https://github.com/israel-bonilla/Instagram-Clone",
    description: "A full-stack clone of Instagram with full authentication and file upload functionality.",
    techsUsed: ["React.js", "Firebase (Firestore Database, Authentication, & Storage)", "CSS3 (w/ BEM naming convention)", "Javascript", "Material UI"],
    features: ["Email/Password Sign-In with Authentication", "Upload images and comments", "Real-time feed update", "Files/images stored in and served from Firebase Storage", "Posts and comments stored in and served from Firebase Firestore Database"],
  },
  {
    id: 106,
    title: "Todo List App",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/todo-app/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/todo-app/2.png",
    ],
    link: "https://todo-list-app-ib.vercel.app",
    source: "https://github.com/israel-bonilla/Todo-List-App",
    description: "A todo list app with add, delete, edit, mark, and unmark functionality. Also meets you with a new inspirational quote each visit.",
    techsUsed: ["React.js", "Redux", "Sass", "Local storage", "Javascript", "Material UI", "Fetch API"],
    features: ["Persistent state saved locally", "New inspirational quote on every refresh brought to you by a custom React hook", "Glassmorphism design", "Smooth animation"],
  },
  {
    id: 107,
    title: "My Portfolio Site",
    // gallery: [],
    // link: "",
    source: "https://github.com/israel-bonilla/portfolio",
    description: "You are here. My latest and one of my proudest builds at the time of writing this: My portfolio site for showcasing my builds and getting in contact with people interested in my skills.",
    techsUsed: ["Next.js", "React", "Sass Modules", "EmailJS", "React Icons", "Javascript"],
    features: ["Modern-ish site design and style", "Interactive and responsive", "Video and image gallery for each item in the projects section", "CSS animations", "Functioning contact/email form"],
  },
  // {
  //   id: 10,
  //   title: "",
  //   gallery: [],
  //   link: "",
  //   source: "",
  //   description: "",
  //   techsUsed: [],
  //   features: [],
  // },
];

export const techs = {
  frontend: [
    { name: "HTML5", icon: "https://icones.pro/wp-content/uploads/2021/05/icone-html-orange.png" },
    { name: "CSS3", icon: "https://www.joykal.com/wp-content/uploads/2019/09/css3.png" },
    { name: "SASS", icon: "https://www.seekpng.com/png/full/377-3772047_sass-logo.png" },
    { name: "JavaScript", icon: "https://cdn.iconscout.com/icon/free/png-256/javascript-2752148-2284965.png" },
    { name: "TypeScript", icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/1200px-Typescript_logo_2020.svg.png" },
    { name: "React.js", icon: "https://cdn.hashnode.com/res/hashnode/image/upload/v1647490619965/P1dsNgj-f1.png" },
    { name: "Next.js", icon: "https://seeklogo.com/images/N/next-js-logo-8FCFF51DD2-seeklogo.com.png" },
    { name: "Recoil", icon: "https://static.codenary.co.kr/framework_logo/recoil.png" },
    { name: "Redux", icon: "https://raw.githubusercontent.com/reduxjs/redux/master/logo/logo.png" },
    { name: "Tailwind CSS", icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/2048px-Tailwind_CSS_Logo.svg.png" },
    { name: "Styled Components", icon: "https://gozattila.dev/static/media/styled_components.a46dc006.png" },
    { name: "jQuery", icon: "https://openjsf.org/wp-content/uploads/sites/84/2019/10/jquery-logo-vertical_large_square.png" },
    { name: "Bootstrap", icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/512px-Bootstrap_logo.svg.png" },
    { name: "Material UI", icon: "https://img.icons8.com/color/12x/material-ui.png" },
    { name: "React Router", icon: "https://miro.medium.com/max/264/1*8hQx0hL2a7eobSlPsa8AtQ.png" },
  ],
  backend: [
    { name: "Node.js", icon: "https://nodejs.org/static/images/logo-hexagon-card.png" },
    { name: "Firebase", icon: "https://static.cdnlogo.com/logos/f/48/firebase.svg" },
    { name: "Supabase", icon: "https://seeklogo.com/images/S/supabase-logo-DCC676FFE2-seeklogo.com.png" },
    { name: "Express", icon: "https://cdn.icon-icons.com/icons2/2699/PNG/512/expressjs_logo_icon_169185.png" },
    { name: "MongoDB", icon: "https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2,f_auto,g_center,q_auto:good/v1/gcs/platform-data-mongodb/events/mon.png" },
    { name: "PostrgeSQL", icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1985px-Postgresql_elephant.svg.png" },
    { name: "SQL", icon: "https://cdn-icons-png.flaticon.com/512/603/603156.png" },
    { name: "GraphQL", icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/GraphQL_Logo.svg/2048px-GraphQL_Logo.svg.png" },
    { name: "Apollo", icon: "https://cdn.worldvectorlogo.com/logos/apollo-graphql-compact.svg" },
    { name: "StepZen", icon: "https://console.dev/img/favicons/stepzen.com.png" },
    { name: "Sanity CMS", icon: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_96102ac6497377cd53da621075fe828e/sanity.png" },
  ],
  other: [
    { name: "Git", icon: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png" },
    { name: "GitHub", icon: "https://cdn-icons-png.flaticon.com/512/25/25231.png" },
    { name: "npm", icon: "https://authy.com/wp-content/uploads/npm-logo.png" },
    { name: "yarn", icon: "https://seeklogo.com/images/Y/yarn-logo-F5E7A65FA2-seeklogo.com.png" },
    { name: "Postman", icon: "https://res.cloudinary.com/postman/image/upload/t_team_logo/v1629869194/team/2893aede23f01bfcbd2319326bc96a6ed0524eba759745ed6d73405a3a8b67a8" },
    { name: "Microsoft Excel", icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Microsoft_Office_Excel_%282019%E2%80%93present%29.svg/1200px-Microsoft_Office_Excel_%282019%E2%80%93present%29.svg.png" }, 
    { name: "Microsoft Word", icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Microsoft_Office_Word_%282019%E2%80%93present%29.svg/1200px-Microsoft_Office_Word_%282019%E2%80%93present%29.svg.png" },
  ],
}