export const projects = [
  {
    id: 101,
    title: "Louphira",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/2.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/3.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/4.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/louphira/5.png",
    ],
    link: "https://louphira.vercel.app/",
    source: "https://github.com/israel-bonilla/Louphira-Shop-Demo",
    description: "Home decoration and design ecommerce store front-end, with Stripe checkout.",
    techsUsed: ["Next.js", "React", "Recoil", "Sass Modules", "Stripe API", "next/router"],
    features: ["Server Side Rendering", "Stripe Checkout", "Shopping cart functionality"],
  },
  {
    id: 102,
    title: "Kajebu",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/2.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/3.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/4.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/kajebu/5.png",
    ],
    link: "https://kajebu.vercel.app/",
    source: "https://github.com/israel-bonilla/kajebu",
    description: "Front-end clone of Kajabi dashboard, an online knowledge business platform.",
    techsUsed: ["Next.js", "React", "Recoil", "Sass Modules", "next/router"],
    features: ["User friendly UI/UX", "Modularized business tools and resources", "Products, pipelines, landing pages, marketing, CRM, and more all-in-one platform."],
  },
  {
    id: 103,
    title: "Weather App",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/weather-app/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/weather-app/2.png",
      "https://links.israelb.xyz/portfolio/project-gallery-items/weather-app/3.png",
    ],
    link: "https://weather-app-ib.vercel.app",
    source: "https://github.com/israel-bonilla/Weather-App",
    description: "A simple weather app that uses a custom React hook with the Geolocation API to broadcast the weather in your location.",
    techsUsed: ["React.js", "Redux", "Tailwind CSS", "Javascript", "Geolocation API", "OpenWeatherMap API", "Fetch API"],
    features: ["Temperature, precipitation, and wind (speed & direction) 24 hour broadcast", "7 day forecast", "Based on user's geolocation", "In Fahrenheit and Celsius", "Humidity indicator"],
  },
  {
    id: 104,
    title: "Hulu (Clone)",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/hulu-clone/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/hulu-clone/2.png",
    ],
    link: "https://hulu-clone-ib.vercel.app",
    source: "https://github.com/israel-bonilla/hulu-clone",
    description: "A front-end clone of Hulu, a movie streaming service.",
    techsUsed: ["Next.js", "React", "Tailwind CSS", "Server Side Rendering", "TMDB API", "Fetch API", "next/router"],
    features: ["Uses movie data from The Movie Database (TMDB)", "Fetches current movies from genres: trending, top rated, action, comedy, horror, and 6 more", "Responsive UI on all screens"],
  },
  {
    id: 105,
    title: "Instagram (Clone)",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/ig-clone/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/ig-clone/2.png",
    ],
    link: "https://ig-clone-ib.vercel.app",
    source: "https://github.com/israel-bonilla/Instagram-Clone",
    description: "A full-stack clone of Instagram with full authentication and file upload functionality.",
    techsUsed: ["React.js", "Firebase (Firestore Database, Authentication, & Storage)", "CSS3 (w/ BEM naming convention)", "Javascript", "Material UI"],
    features: ["Email/Password Sign-In with Authentication", "Upload images and comments", "Real-time feed update", "Files/images stored in and served from Firebase Storage", "Posts and comments stored in and served from Firebase Firestore Database"],
  },
  {
    id: 106,
    title: "Todo List App",
    gallery: [
      "https://links.israelb.xyz/portfolio/project-gallery-items/todo-app/1.mp4",
      "https://links.israelb.xyz/portfolio/project-gallery-items/todo-app/2.png",
    ],
    link: "https://todo-list-app-ib.vercel.app",
    source: "https://github.com/israel-bonilla/Todo-List-App",
    description: "A todo list app with add, delete, edit, mark, and unmark functionality. Also meets you with a new inspirational quote each visit.",
    techsUsed: ["React.js", "Redux", "Sass", "Local storage", "Javascript", "Material UI", "Fetch API"],
    features: ["Persistent state saved locally", "New inspirational quote on every refresh brought to you by a custom React hook", "Glassmorphism design", "Smooth animation"],
  },
  {
    id: 107,
    title: "My Portfolio Site",
    // gallery: [],
    // link: "",
    source: "https://github.com/israel-bonilla/portfolio",
    description: "You are here. My latest and one of my proudest builds at the time of writing this: My portfolio site for showcasing my builds and getting in contact with people interested in my skills.",
    techsUsed: ["Next.js", "React", "Sass Modules", "EmailJS", "React Icons", "Javascript"],
    features: ["Modern-ish site design and style", "Interactive and responsive", "Video and image gallery for each item in the projects section", "CSS animations", "Functioning contact/email form"],
  },
  // {
  //   id: 10,
  //   title: "",
  //   gallery: [],
  //   link: "",
  //   source: "",
  //   description: "",
  //   techsUsed: [],
  //   features: [],
  // },
];